language: csharp
mono: none
dotnet: 2.2
dist: bionic
script:
 - dotnet restore
 - dotnet build --configuration "Release"
 - dotnet test --configuration "Release" EmbeddedResources.Tests/EmbeddedResources.Tests.csproj

branches:
  only:
  - master
  - develop