language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore
 - dotnet build --configuration "Release"
 - dotnet test --configuration "Release" EmbeddedResources.Tests/EmbeddedResources.Tests.csproj

branches:
  only:
  - master
  - develop